### ISSUE TITLE
Keep track of TODO's

### ISSUE THREAD

**Issue by tjdevries** [tjdevries/vim-secret-markers#1]
Just a list of TODO's for the project before I consider it "ready to go"
- [ ] Handle white space between text and beginning of comment
  - For example, `def fun(a):  # comment {{{ fold`, will turn into `def fun(a):__` (where the `_` are added for empahsis`
- [ ] Gracefully handle files that do not have matching fold markers for all scenarios
- [ ] Perhaps clean up `fold_combinations`.
  - Does not really do anything currently.
  - I probably want to keep the logic, because it is helpful to know for later if I keep track of fold levels or anything
- [ ] Integrate git functionality
  - Wow this will be difficult.
- [ ] Allow configuration of save location / format for the marker save file
- [ ] Add VIM documentation
